export const TRUE_ISOMETRIC_CAMERA_YAW_DEGREES = 45;
export const TRUE_ISOMETRIC_CAMERA_ELEVATION_DEGREES = 35.264389682754654;
export const TRUE_ISOMETRIC_SCREEN_EDGE_DEGREES = 30;

export const TILE_CANVAS_WIDTH = 96;
export const TILE_CANVAS_HEIGHT = 140;
export const TILE_TOP_WIDTH = TILE_CANVAS_WIDTH;
export const TILE_TOP_HEIGHT =
  TILE_TOP_WIDTH * Math.tan((TRUE_ISOMETRIC_SCREEN_EDGE_DEGREES * Math.PI) / 180);
export const TILE_STEP_X = TILE_TOP_WIDTH / 2;
export const TILE_STEP_Y = TILE_TOP_HEIGHT / 2;

export const LEGACY_TILE_TOP_HEIGHT = 54;
export const LEGACY_TILE_SCREEN_EDGE_DEGREES =
  Math.atan((LEGACY_TILE_TOP_HEIGHT / 2) / (TILE_TOP_WIDTH / 2)) * (180 / Math.PI);

