{{- if eq (include "chess-tactics.renderWarm" .) "true" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount }}
  namespace: {{ include "chess-tactics.namespace" . }}
{{- end }}
