// React app entry — replaces the legacy app.js string-HTML router. index.html
// loads this module. Bundles the design tokens (style.css), starts background
// music, and mounts the React router. (Account/auth chrome lives in the React
// app-shell title bar now — src/ui/shared/HeaderAccountCluster.)
import './style.css';
// Generated by scripts/nine-slice-kit.mjs — carries each 9-slice asset's `content`
// into CSS vars (e.g. --settings-tab-content). Regenerated on apply / dev Save.
import './generated/nine-slice.css';
import { createRoot } from 'react-dom/client';
import { App } from './ui/App';
// @ts-ignore — bgm.js is untyped legacy JS, imported for its side-effecting init.
import { initBgm } from './bgm.js';

// Stale-deploy self-heal. index.html is served no-cache and the chunks are
// content-hashed + immutable — correct — but that does NOT save a tab that
// loaded an older build and then client-side-navigates to a route whose chunk
// hash a newer deploy has replaced: the dynamic import 404s and the route goes
// blank. Vite fires `vite:preloadError` for exactly that. Reload once to fetch
// the fresh index.html + current chunks. The 10s window breaks any reload loop
// from a chunk that is genuinely broken (not merely stale).
window.addEventListener('vite:preloadError', (event) => {
  const KEY = 'ct:preload-reload-at';
  const last = Number(sessionStorage.getItem(KEY) || '0');
  if (Date.now() - last < 10_000) return; // just reloaded — real error, let it surface
  sessionStorage.setItem(KEY, String(Date.now()));
  event.preventDefault();
  window.location.reload();
});

// The shell ships hidden (avoids an unstyled flash); reveal it once JS runs.
const shell = document.querySelector('.shell');
if (shell instanceof HTMLElement) shell.style.visibility = 'visible';

try { initBgm(); } catch { /* background music is decorative */ }

const root = document.getElementById('root');
if (root) createRoot(root).render(<App />);
