import { useEffect, useMemo, useState, type CSSProperties, type ReactElement, type ReactNode } from 'react';
import {
  acceptLiveMediaVersions,
  fetchAdminLiveMediaCatalog,
  reviewLiveMediaVersion,
  type AdminLiveMediaCatalog,
  type AdminLiveMediaVersion,
} from '../net/liveMediaAdmin';
import { StudioCatalogCard } from './studio/StudioCatalogCard';
import { StudioStepper } from './studio/StudioStepper';
import { ChromeButton } from './shared/ChromeButton';

/**
 * Candidate backdrops for the full-screen workspace pages, read straight from the
 * live-media catalog. Read-only art: browsed as a Catalog grid and inspected one-big in
 * the shared Viewer, per docs/studio-control-architecture.md — the Catalog's main pane is
 * the grid, and "one item big + Details readout" is the Viewer's job, never the catalog's.
 *
 * Plates are authored at 640x360 and ship at 4x (2560x1440) with nearest-neighbour
 * scaling. Browsing and viewing never change what the game paints; only the Viewer's
 * explicit install control does, and only for the screen the candidate was authored for.
 */
const SCREEN_ART_SLOT = /^review\/run-screen-art\/([a-z][a-z0-9-]*)\/([a-z][a-z0-9-]*)\.png$/;

const SCREEN_LABELS: Record<string, string> = {
  deployment: 'Deployment',
  sell: 'Sell Units',
  army: 'Army',
  relics: 'Lipsana',
  victory: 'Victory — War won',
  events: 'Level Editor — Events',
  // Spolia set (docs/background-set-briefs.md): four scene directions for the
  // conflict-opening relic screen, each generated by both sources so the pair sits
  // adjacent in the grid. Card titles truncate around 14 characters, so the
  // distinguishing noun goes after a short shared prefix, never before it.
  'spolia-ruin': 'Spolia · Nave',
  'spolia-inventory': 'Spolia · Table',
  'spolia-crossing': 'Spolia · Yard',
  'spolia-field': 'Spolia · Field',
};

const GENERATOR_LABELS: Record<string, string> = {
  codex: 'Codex (gpt-image)',
  pixellab: 'PixelLab (pro)',
};

export interface ScreenArtCandidate {
  id: string;
  screen: string;
  screenLabel: string;
  generator: string;
  generatorLabel: string;
  version: AdminLiveMediaVersion;
}

/** Newest candidate per (screen, generator), ordered by screen then generator. */
export function screenArtCandidates(catalog: AdminLiveMediaCatalog): ScreenArtCandidate[] {
  const newest = new Map<string, ScreenArtCandidate>();
  for (const version of catalog.versions) {
    const match = SCREEN_ART_SLOT.exec(version.slot ?? '');
    if (!match || !version.media) continue;
    const [, screen, generator] = match;
    const id = `${screen}--${generator}`;
    const prior = newest.get(id);
    if (!prior || version.rowRevision > prior.version.rowRevision) {
      newest.set(id, {
        id,
        screen,
        screenLabel: SCREEN_LABELS[screen] ?? screen,
        generator,
        generatorLabel: GENERATOR_LABELS[generator] ?? generator,
        version,
      });
    }
  }
  return [...newest.values()].sort((left, right) => (
    left.screenLabel.localeCompare(right.screenLabel) || left.generator.localeCompare(right.generator)
  ));
}

export function useScreenArtCatalog(): {
  items: ScreenArtCandidate[];
  catalog: AdminLiveMediaCatalog | null;
  loading: boolean;
  error: string;
  refresh: () => void;
} {
  const [catalog, setCatalog] = useState<AdminLiveMediaCatalog | null>(null);
  const [error, setError] = useState('');
  const [nonce, setNonce] = useState(0);
  useEffect(() => {
    let active = true;
    void fetchAdminLiveMediaCatalog()
      .then((next) => { if (active) setCatalog(next); })
      .catch((reason) => { if (active) setError(reason instanceof Error ? reason.message : String(reason)); });
    return () => { active = false; };
  }, [nonce]);
  const items = useMemo(() => catalog ? screenArtCandidates(catalog) : [], [catalog]);
  return { items, catalog, loading: !catalog && !error, error, refresh: () => setNonce((value) => value + 1) };
}

export function findScreenArt(items: readonly ScreenArtCandidate[], id: string): ScreenArtCandidate | null {
  return items.find((item) => item.id === id) ?? null;
}


/** The runtime slot a screen's backdrop is installed into, when that screen has one. */
const RUNTIME_SLOT_BY_SCREEN: Record<string, string> = {
  victory: 'ui/workspaces/run-victory/background.png',
  events: 'ui/workspaces/level-editor-events/background.png',
};

/**
 * The owner's install decision. The bytes are already uploaded to the screen's runtime
 * slot as a candidate; installing records approval of these exact bytes and accepts the
 * version, which is what makes the screen paint it. Review alone never installs.
 */
function ScreenArtInstall({
  candidate,
  catalog,
  onInstalled,
}: {
  candidate: ScreenArtCandidate;
  catalog: AdminLiveMediaCatalog;
  onInstalled: () => void;
}): ReactElement | null {
  const [busy, setBusy] = useState(false);
  const [status, setStatus] = useState('');
  const runtimeSlot = RUNTIME_SLOT_BY_SCREEN[candidate.screen];
  if (!runtimeSlot) return null;

  const slot = catalog.slots.find((entry) => entry.slot === runtimeSlot) ?? null;
  const pending = catalog.versions
    .filter((version) => version.slot === runtimeSlot && version.media)
    .sort((left, right) => right.rowRevision - left.rowRevision)[0] ?? null;
  const live = slot?.activeVersionId ?? null;
  const installed = pending && live === pending.id;

  const install = async (): Promise<void> => {
    if (busy || !pending?.media) return;
    setBusy(true);
    setStatus('Recording approval for these exact bytes…');
    try {
      const reviewed = await reviewLiveMediaVersion({
        id: pending.id,
        expectedRevision: pending.rowRevision,
        notes: `Approved ${candidate.screenLabel} backdrop (${candidate.generatorLabel}) from the Screen Art viewer.`,
        surfaceUrl: window.location.href,
        evidence: {
          schema: 'live-media-owner-proof-v1',
          versionId: pending.id,
          contentSha256: pending.media.sha256,
          slot: runtimeSlot,
          canonicalScale: 1,
          surfaceKind: `${candidate.screenLabel} workspace background reviewed at pane size`,
        },
      });
      setStatus('Installing…');
      await acceptLiveMediaVersions([{
        id: reviewed.id,
        expectedRevision: reviewed.rowRevision,
        expectedSlotRevision: slot?.rowRevision ?? 0,
        expectedActiveVersionId: slot?.activeVersionId ?? null,
      }]);
      setStatus(`Installed. ${candidate.screenLabel} now paints this backdrop.`);
      onInstalled();
    } catch (reason) {
      setStatus(reason instanceof Error ? `Install failed: ${reason.message}` : 'Install failed.');
    } finally {
      setBusy(false);
    }
  };

  return (
    <section className="screen-art-install" aria-label="Install this backdrop">
      <h3>Install on {candidate.screenLabel}</h3>
      {!pending ? (
        <p>No candidate is uploaded to <code>{runtimeSlot}</code> yet.</p>
      ) : installed ? (
        <p role="status">Installed — {candidate.screenLabel} paints this backdrop now.</p>
      ) : (
        <>
          <p>
            These bytes are uploaded to <code>{runtimeSlot}</code> and waiting on your approval.
            Installing records that decision and makes the screen paint them.
          </p>
          <ChromeButton
            unit="inner-text-button"
            disabled={busy}
            data-testid="install-screen-art"
            onClick={() => { void install(); }}
          >
            {busy ? 'Installing…' : `Use on ${candidate.screenLabel}`}
          </ChromeButton>
        </>
      )}
      {status ? <p role="status">{status}</p> : null}
    </section>
  );
}

/** Catalog main pane: the grid. Selection lives here, not in the Controls rail. */
export function ScreenArtCatalog({
  items,
  loading,
  error,
  search,
  zoom,
  selected,
  onSelect,
  onView,
}: {
  items: readonly ScreenArtCandidate[];
  loading: boolean;
  error: string;
  search: string;
  zoom: number;
  selected: string;
  onSelect: (id: string) => void;
  onView: (id: string) => void;
}): ReactElement {
  const query = search.trim().toLowerCase();
  const visible = items.filter((item) => !query
    || `${item.screenLabel} ${item.generatorLabel}`.toLowerCase().includes(query));

  return (
    <section className="tileset-studio-main is-headless">
      <section className="tileset-studio-tab-panel">
        <div className="tileset-asset-sections" style={{ '--tile-zoom': zoom } as CSSProperties}>
          {error ? <p className="tileset-catalog-note" role="alert">{error}</p> : null}
          {loading ? <p className="tileset-catalog-note" role="status">Loading screen-art candidates…</p> : null}
          {!loading && !error && !visible.length
            ? <p className="tileset-catalog-note">No screen-art candidates match the current search.</p>
            : null}
          {visible.length ? (
            <div className="tileset-studio-grid" data-testid="screen-art-grid">
              {visible.map((item) => (
                <StudioCatalogCard
                  key={item.id}
                  title={item.screenLabel}
                  badge={item.generatorLabel}
                  image={item.version.media!.url}
                  imageClassName="screen-art-card-image"
                  selected={selected === item.id}
                  onSelect={() => onSelect(item.id)}
                  onInspect={() => onView(item.id)}
                  inspectLabel={`View ${item.screenLabel} — ${item.generatorLabel}`}
                  metaExtra={<span className="asset-prov is-original">
                    {item.version.status === 'candidate' ? 'candidate' : item.version.status}
                  </span>}
                />
              ))}
            </div>
          ) : null}
        </div>
      </section>
    </section>
  );
}

/** Viewer stage: one plate as large as the pane allows, plus the Details readout. */
export function ScreenArtViewer({
  items,
  id,
  header,
  catalog,
  onInstalled,
  onSelect,
}: {
  items: readonly ScreenArtCandidate[];
  id: string;
  header?: ReactNode;
  catalog: AdminLiveMediaCatalog | null;
  onInstalled: () => void;
  onSelect: (id: string) => void;
}): ReactElement {
  const found = id ? findScreenArt(items, id) : null;
  const empty = 'No candidate selected — pick a card in the Screen Art catalog.';
  return (
    <>
      <section className="al-lab-main" aria-label="Screen art preview">
        {!found ? <p className="al-lab-empty">{empty}</p> : (
          <div className="al-lab-stages">
            <figure className="al-stage screen-art-stage" data-testid="screen-art-stage" data-screen={found.screen} data-generator={found.generator}>
              <img
                src={found.version.media!.url}
                alt={`${found.screenLabel} backdrop by ${found.generatorLabel}`}
                data-version-id={found.version.id}
              />
              <figcaption>{found.screenLabel} — {found.generatorLabel}</figcaption>
            </figure>
          </div>
        )}
      </section>
      <aside className="tileset-view-controls" aria-label="Screen art controls">
        <section className="tileset-inspector-section">
          <h2>Controls</h2>
          <div className="tileset-control-stack">
            {header}
            <StudioStepper
              itemNoun="candidate"
              label="Candidate"
              onChange={onSelect}
              options={items.map((item) => ({ id: item.id, label: `${item.screenLabel} — ${item.generatorLabel}` }))}
              value={found?.id ?? ''}
            />
            {found ? (
              <dl className="al-meta">
                <div><dt>Screen</dt><dd>{found.screenLabel}</dd></div>
                <div><dt>Generator</dt><dd>{found.generatorLabel}</dd></div>
                <div><dt>Native</dt><dd>{found.version.media!.width ?? '?'}×{found.version.media!.height ?? '?'}</dd></div>
                <div><dt>Ships at</dt><dd>4× (2560×1440)</dd></div>
                <div><dt>Status</dt><dd>{found.version.status === 'candidate' ? 'candidate · not installed' : found.version.status}</dd></div>
                <div><dt>Slot</dt><dd>{found.version.slot}</dd></div>
                <div><dt>Revision</dt><dd>{found.version.rowRevision}</dd></div>
                <div><dt>SHA-256</dt><dd>{found.version.media!.sha256}</dd></div>
              </dl>
            ) : <p className="tileset-catalog-note">{empty}</p>}
            {found && catalog ? (
              <ScreenArtInstall candidate={found} catalog={catalog} onInstalled={onInstalled} />
            ) : null}
          </div>
        </section>
      </aside>
    </>
  );
}
